

/**
PROPIEDADES DE LAS COLUMNAS DE LA TABLA
Principales o Referenciales:
Primary Key: clave principal de la tabla.
Foreign Key: Clave Foranea es clave primaria de otra tabla, se usa para referenciar o relacionar a otra tabla.
References NOMBRE_TABLA(COLUMNA)
Unique: Campo que no repite valores
Identity(1,1): Autonumérico que inicia desde 1 y se incrementa en 1
Not Null: Campo que no acepta valor null o vacio o NULL acepta valor nulo


Segun el tipo de valor que se carga en el campo.
TEXTO: 
VARCHAR(30), almacena caracteres hasta el total del campo 30, el resto lo descarta.

NUMERO:
INT: Número entero.
BIGINT: Número entero.
FLOAT: Número decimal, racional.
DECIMAL: Número con coma.
MONEY: Número que expresa valor monetario.
BIGMONEY: Número que expresa pequeño valor monetario.
INTEGER: 

FECHA:
TIME: Hora, minutos y segundos.
DATE: Fecha desde 01/01/1001 al 31/12/9999
SMALLDATETIME: Fecha desde 01/01/1900  00:00:00 al 06/06/2079 23:59:59 
DATETIME: Fecha desde 01/01/1000  00:00:00 al 31/12/9999 23:59:59 

RESTRICCIONES:
INUQUE

CONSULTA:
select GATEDATE()                           => expresa la fecha y hora del sistema.
select name from sysobjects where type ='U' => muestra la tablas de una base de datos
-Use master
-go
-drop database NOMBRE_BASE_DATOS
-go                                         => elimina la base de datos vacia


MODIFICAR TABLA O COLUMA LUEGO DE SER CREADA
https://www.1keydata.com/es/sql/sql-alter-table.php
Cambiar propiedades de la tabla por columna
ALTER TABLE NOMBRETABLA ALTER COLUMN NOMBRECOLUMNA PROPIEDADES(..)
Cambiar el nombre de un campo
ALTER TABLE 'NOMBRE_TABLA.NOMBRE_COLUMNA', NOMBRE_COLUMNA_NUEVO', 'COLUMN' VER??
Agregar Nuevo Campo
ALTER TABLE NOBRE_TABLA ADD NOMBRE_COLUMN_NUEVO PROPIEDADES (INT NOT NULL IDENTITY(1,1) ETC)
Clausurar Primary Key
CONSTRAINT [NOMBRE_COLUMNA] PRIMERY KEY CLUSTERED
Agregar restricciones
ALTER TABLE NOMBRE_TABLA ADD CONSTRAINT NOMBRE_RESTRICCION()
Eliminar una columna
ALTER TABLE NOMBRE_TABLA DROP “NOMBRE_COLUMNA”
Cambiar el nombre de una columna
ALTER TABLE NOMBRE_TABLA CHANGE “NOMBRE_COLUMNA” “NOMBRE_COLUMNA_NUEVO” “PROPIEDADES tipos de datos para la nueva columna".
Cambiar el tipo de datos para una columna
ALTER TABLE NOMBRE_TABLA MODIFY “NOMBRE_COLUMNA” “PROPIEDADES nuevo tipo de datos”






INSERTAR DATOS EN UNA TABLA
INSERT INTO NOMBRETABLA(CAMPO1_TEXTO, CAMPO2_INT, CAMPO3_FECHA,....) VALUES('TEXTO', 12345, GETDATE() Ó '01/01/2021',....)
Se debe respetar el orden de las columnas y el tipo de dato a ingresar (int, date, varchar, etc)






*/

select name from sysobjects where type ='U' -- Muestra las tablas que existen en la base de datos

use master
go
drop database tpcsysacad
go

create DATABASE TPCSYSACAD --crea la base de datos
GO
USE TPCSYSACAD
GO
DROP TABLE ALUMNOS
CREATE TABLE ALUMNOS( --crea la tabla de la base de datos
    ID_ALUMNO INT PRIMARY KEY IDENTITY(1,1),
	CUIL VARCHAR (14) NOT NULL UNIQUE,
    APELLIDO_NOMBRE VARCHAR(50) NOT NULL,
	NACIONALIDAD VARCHAR(30) NOT NULL,
    FECHA_NAC DATE NOT NULL CHECK(FECHA_NAC < GETDATE()),
    MAIL VARCHAR(30) NOT NULL,
	DOMICILIO VARCHAR(50),
	LOCALIDAD_PCIA VARCHAR(50),
    USUARIO VARCHAR(20) DEFAULT(NULL),
	ESTADO INT NOT NULL DEFAULT(0) CHECK(ESTADO = 0 OR ESTADO = 1 OR ESTADO = 2) --EN PRIMERA INSTANCIA SE COLOCA 0 = NO HAB, 1 = ALTA, 2 = BAJA SIN CARRERA ASOC.
)
GO


GO
DROP TABLE DOCENTES
CREATE TABLE DOCENTES(
	ID_DOCENTE INT PRIMARY KEY IDENTITY(1,1),
	CUIL VARCHAR(14) NOT NULL UNIQUE,
	APELLIDO_NOMBRE VARCHAR(50) NOT NULL,
	NACIONALIDAD VARCHAR(30) NOT NULL,
	FECHA_NAC DATE NOT NULL CHECK(FECHA_NAC < GETDATE()),
	MAIL VARCHAR (30) NOT NULL,
	DOMICILIO VARCHAR(50),
	LOCALIDAD_PCIA VARCHAR(50),
	USUARIO VARCHAR(20) DEFAULT(NULL),
	ESTADO INT NOT NULL DEFAULT(0) CHECK(ESTADO = 0 OR ESTADO = 1 OR ESTADO = 2)
)
GO

CREATE TABLE CARRERAS(
	ID_CARRERA VARCHAR(10) PRIMARY KEY,
	NOMBRE_CARRERA VARCHAR(100) NOT NULL UNIQUE,
	PLAN_AÑO VARCHAR(5) NOT NULL,
	DOC_HABILITANTE VARCHAR(50) NOT NULL, --RESOLUCION QUE HABILITE LA CARRERA
	ESTADO BIT DEFAULT(1)
)
GO

CREATE TABLE MATERIAS(
	ID_MATERIA VARCHAR(10) PRIMARY KEY,
	NOMBRE_MATERIA VARCHAR(50) NOT NULL,
	CARGA_HORARIA_MINIMA INT NOT NULL CHECK(CARGA_HORARIA_MINIMA > 0),
	CARRERA VARCHAR(10) NOT NULL FOREIGN KEY REFERENCES CARRERAS(ID_CARRERA),
	AÑO_CURSO INT NOT NULL CHECK(AÑO_CURSO = 1 OR AÑO_CURSO = 2),
	CUATRIMESTRE INT NOT NULL CHECK(CUATRIMESTRE = 1 OR CUATRIMESTRE = 2),
	ESTADO BIT NOT NULL DEFAULT(1)
)
GO

CREATE TABLE INSC_ALUM_CARRERA( --INSCRIPCION DE ALUMNO A LA CARRERA
	ID_INSCRIPCION_CARRERA INT IDENTITY (1,1),
	ALUMNO INT NOT NULL FOREIGN KEY REFERENCES ALUMNOS(ID_ALUMNO),
	CARRERA VARCHAR(10) NOT NULL FOREIGN KEY REFERENCES CARRERAS(ID_CARRERA),
	AÑO INT NOT NULL DEFAULT (YEAR(GETDATE())),
	CUATRIMESTRE INT CHECK(CUATRIMESTRE = 1 OR CUATRIMESTRE = 2),
	ESTADO BIT NOT NULL DEFAULT(1)
)
ALTER TABLE INSC_ALUM_CARRERA ADD CONSTRAINT PK_INSC_ALUMN_CARRERA PRIMARY KEY(ALUMNO, CARRERA)
GO

CREATE TABLE USUARIOS(
    ID_USUARIO INT PRIMARY KEY IDENTITY(1,1),
	USUARIO VARCHAR(10) NOT NULL UNIQUE,
    PASSWARD VARCHAR(10) NOT NULL,
    TIPOUSUARIO int NOT NULL  --SE PUEDE HACER UNA TABLA DE TIPO DE SUSUARIOS Y RELACIONARLA
	--CHECK(TIPOUSUARIO = 'ADMINISTRACION' OR TIPOUSUARIO = 'ALUMNO' OR TIPOUSUARIO = 'PROFESOR' OR TIPOUSUARIO = 'ADMINISTRADOR')
)
GO

ALTER TABLE USUARIOS ALTER COLUMN USUARIO VARCHAR(17) NOT NULL FOREIGN KEY REFERENCES ALUMNOS(USUARIO); 
ALTER TABLE USUARIOS ALTER COLUMN PASSWARD VARCHAR(14) NOT NULL; 



ALTER TABLE USUARIOS CHANGE USUARIO USUARIO VARCHAR(17) NOT NULL UNIQUE;
alter table usuarios MODIFY usuario varchar(17) not null unique

ALTER TABLE NOMBRE_TABLAalter MODIFY “NOMBRE_COLUMNA” “PROPIEDADES nuevo tipo de datos”

CREATE TABLE INSC_ALUM_MATERIA(
	ID_INSCRIPCION_MATERIA INT IDENTITY(1,1),
	ALUMNO INT NOT NULL FOREIGN KEY REFERENCES ALUMNOS(ID_ALUMNO),
	MATERIA VARCHAR(10) NOT NULL FOREIGN KEY REFERENCES MATERIAS(ID_MATERIA),
	ESTADO BIT NOT NULL DEFAULT(1)
)
GO

--TODAVIA NO AGREGUE A LA BASE DE DATOS ============= A DEFINIR ..................................................
USE TPCSYSACAD
insert into ALUMNOS(CUIL, APELLIDO_NOMBRE, NACIONALIDAD, FECHA_NAC, MAIL, DOMICILIO, LOCALIDAD_PCIA) 
VALUES('24-21453000-8', 'GOMEZ FABIAN', 'ARGENTINE', '03-01-1969', 'lu8ebuhfg@hotmail.com', 'Estrada 1300', 'Victoria - BsAs' )
insert into DOCENTES(CUIL, APELLIDO_NOMBRE, NACIONALIDAD, FECHA_NAC, MAIL, DOMICILIO, LOCALIDAD_PCIA) 
VALUES('23-21453904-8', 'GOMEZ FABIAN', 'ARGENTINE', '03-01-1969', 'lu8ebuhfg@hotmail.com', 'Estrada 1300', 'Victoria - BsAs' )

insert into ALUMNOS(CUIL, APELLIDO_NOMBRE, NACIONALIDAD, FECHA_NAC, MAIL, DOMICILIO, LOCALIDAD_PCIA) 
VALUES('20-44261358-8', 'GOMEZ COTI ZELATI', 'ARGENTINE', '07-19-1970', 'luSD8ebuhfg@hotmail.com', 'Estrada 3374', 'Victoria - BsAs' )

SELECT USUARIO, CUIL FROM ALUMNOS WHERE ID_ALUMNO = 18

INSERT INTO USUARIOS(USUARIO, PASSWARD, TIPOUSUARIO) 
VALUES('AL.24-21453000-8', '24-21453000-8', 2)

UPDATE ALUMNOS SET ESTADO = 2 WHERE ID_ALUMNO = 5 

UPDATE ALUMNOS SET ESTADO = 0

select 'al.'+cuil from ALUMNOS where ID_ALUMNO = 1
UPDATE ALUMNOS SET USUARIO = 'AL.'+CUIL


UPDATE DOCENTES SET ESTADO = 2 WHERE ID_DOCENTE = 4
UPDATE DOCENTES SET ESTADO = 0
UPDATE CARRERAS SET ESTADO =1

SELECT * FROM ALUMNOS
SELECT * FROM USUARIOS
SELECT * FROM DOCENTES


SELECT ID_CARRERA, NOMBRE_CARRERA, PLAN_AÑO, DOC_HABILITANTE, ESTADO FROM CARRERAS
SELECT * FROM MATERIAS
SELECT ID_MATERIA, NOMBRE_MATERIA, CARGA_HORARIA_MINIMA, CARRERA, AÑO_CURSO, CUARTRIMESTRE, ESTADO FROM MATERIAS WHERE ESTADO != 0
SELECT * FROM COMISIONES
SELECT ID_ALUMNO, CUIL, APELLIDO_NOMBRE, NACIONALIDAD, FECHA_NAC, MAIL, DOMICILIO, LOCALIDA_PCIA, USUARIO, ESTADO FROM ALUMNOS
SELECT ID_DOCENTE, CUIL, APELLIDO_NOMBRE, NACIONALIDAD, FECHA_NAC, MAIL, DOMICILIO, LOCALIDAD_PCIA, USUARIO, ESTADO FROM DOCENTES
SELECT ID_MATERIA, NOMBRE_MATERIA, CARGA_HORARIA_MINIMA, CARRERA, AÑO_CURSO, CUATRIMESTRE, ESTADO FROM MATERIAS WHERE ESTADO != 0
SELECT USUARIO, TIPOUSUARIO FROM USUARIOS
go

/**CREATE TABLE TIPOSUSUARIOS(
    ID INT PRIMARY KEY IDENTITY(1,1),
    DESCRIPCION VARCHAR(15) NOT NULL
)*/

DROP TABLE COMISIONES
CREATE TABLE COMISIONES(
	ID_COMISION INT NOT NULL,
	CARRERA VARCHAR(10) NOT NULL FOREIGN KEY REFERENCES CARRERAS(ID_CARRERA),
	MATERIA VARCHAR(10) NOT NULL FOREIGN KEY REFERENCES MATERIAS(ID_MATERIA),
	INICIO DATE NOT NULL,
	FINALIZA DATE NOT NULL,
	ESTADO BIT NOT NULL DEFAULT(1)	
)
ALTER TABLE COMISIONES ADD CONSTRAINT PK_COMISIONES PRIMARY KEY(CARRERA, MATERIA, INICIO)
GO 

--====================            DATOS CARGADOS       ===============================================

--USUARIOS
INSERT INTO USUARIOS VALUES('ADMIN', 'ADMIN', 1 )
INSERT INTO USUARIOS VALUES('PROF',  'PROF',  2 )
INSERT INTO USUARIOS VALUES('ALUM',  'ALUM',  3 )

--CARRERA
INSERT INTO CARRERAS(ID_CARRERA, NOMBRE_CARRERA, PLAN_AÑO, DOC_HABILITANTE, ESTADO)
VALUES('TUPR', 'Tecnicatura Universitaria en Programación', '2003', 'RESOLUCION 50/2000 MIN EDUCACION')

-- MATERIAS
INSERT INTO MATERIAS(ID_MATERIA, NOMBRE_MATERIA, CARGA_HORARIA_MINIMA, CARRERA, AÑO_CURSO, CUATRIMESTRE) 
VALUES('ARSO', 'Arquitectura y Sistemas Operativos', 100, 'TUPR', 1, 1)
INSERT INTO MATERIAS(ID_MATERIA, NOMBRE_MATERIA, CARGA_HORARIA_MINIMA, CARRERA, AÑO_CURSO, CUATRIMESTRE) 
VALUES('ESTA', 'Estadística', 100, 'TUPR', 1, 1)
INSERT INTO MATERIAS(ID_MATERIA, NOMBRE_MATERIA, CARGA_HORARIA_MINIMA, CARRERA, AÑO_CURSO, CUATRIMESTRE) 
VALUES('ING1', 'Inglés I', 100, 'TUPR', 1, 1)
INSERT INTO MATERIAS(ID_MATERIA, NOMBRE_MATERIA, CARGA_HORARIA_MINIMA, CARRERA, AÑO_CURSO, CUATRIMESTRE) 
VALUES('ING2', 'Inglés II', 100, 'TUPR', 1, 2)
INSERT INTO MATERIAS(ID_MATERIA, NOMBRE_MATERIA, CARGA_HORARIA_MINIMA, CARRERA, AÑO_CURSO, CUATRIMESTRE) 
VALUES('LAB1', 'Laboratorio de Computación I', 100, 'TUPR', 1, 1)
INSERT INTO MATERIAS(ID_MATERIA, NOMBRE_MATERIA, CARGA_HORARIA_MINIMA, CARRERA, AÑO_CURSO, CUATRIMESTRE) 
VALUES('LAB2', 'Laboratorio de Computación II', 100, 'TUPR', 1, 1)
INSERT INTO MATERIAS(ID_MATERIA, NOMBRE_MATERIA, CARGA_HORARIA_MINIMA, CARRERA, AÑO_CURSO, CUATRIMESTRE) 
VALUES('MATE', 'Matemática', 100, 'TUPR', 1, 1)
INSERT INTO MATERIAS(ID_MATERIA, NOMBRE_MATERIA, CARGA_HORARIA_MINIMA, CARRERA, AÑO_CURSO, CUATRIMESTRE) 
VALUES('METI', 'Metodología de la Investigación', 100, 'TUPR', 1, 1)
INSERT INTO MATERIAS(ID_MATERIA, NOMBRE_MATERIA, CARGA_HORARIA_MINIMA, CARRERA, AÑO_CURSO, CUATRIMESTRE) 
VALUES('PRG1', 'Programación I', 100, 'TUPR', 1, 1)
INSERT INTO MATERIAS(ID_MATERIA, NOMBRE_MATERIA, CARGA_HORARIA_MINIMA, CARRERA, AÑO_CURSO, CUATRIMESTRE) 
VALUES('PRG2', 'Programación II', 100, 'TUPR', 1, 1)
INSERT INTO MATERIAS(ID_MATERIA, NOMBRE_MATERIA, CARGA_HORARIA_MINIMA, CARRERA, AÑO_CURSO, CUATRIMESTRE) 
VALUES('SPRD', 'Sistemas de Procesamiento de Datos', 100, 'TUPR', 1, 1)
INSERT INTO MATERIAS(ID_MATERIA, NOMBRE_MATERIA, CARGA_HORARIA_MINIMA, CARRERA, AÑO_CURSO, CUATRIMESTRE) 
VALUES('DABD', 'Diseño y Administración de Bases de Dato', 100, 'TUPR', 1, 1)
INSERT INTO MATERIAS(ID_MATERIA, NOMBRE_MATERIA, CARGA_HORARIA_MINIMA, CARRERA, AÑO_CURSO, CUATRIMESTRE) 
VALUES('INVE', 'Elementos de Investigación Operativa', 100, 'TUPR', 1, 1)
INSERT INTO MATERIAS(ID_MATERIA, NOMBRE_MATERIA, CARGA_HORARIA_MINIMA, CARRERA, AÑO_CURSO, CUATRIMESTRE) 
VALUES('LAB3', 'Laboratorio de Computación III', 100, 'TUPR', 1, 1)
INSERT INTO MATERIAS(ID_MATERIA, NOMBRE_MATERIA, CARGA_HORARIA_MINIMA, CARRERA, AÑO_CURSO, CUATRIMESTRE) 
VALUES('LAB4', 'Laboratorio de Computación IV', 100, 'TUPR', 1, 1)
INSERT INTO MATERIAS(ID_MATERIA, NOMBRE_MATERIA, CARGA_HORARIA_MINIMA, CARRERA, AÑO_CURSO, CUATRIMESTRE) 
VALUES('LEGI', 'Legislación', 100, 'TUPR', 1, 1)
INSERT INTO MATERIAS(ID_MATERIA, NOMBRE_MATERIA, CARGA_HORARIA_MINIMA, CARRERA, AÑO_CURSO, CUATRIMESTRE) 
VALUES('SIS1', 'Metodología de Sistemas I', 100, 'TUPR', 1, 1)
INSERT INTO MATERIAS(ID_MATERIA, NOMBRE_MATERIA, CARGA_HORARIA_MINIMA, CARRERA, AÑO_CURSO, CUATRIMESTRE) 
VALUES('OCEM', 'Organización Contable de la Empresa', 100, 'TUPR', 1, 1)
INSERT INTO MATERIAS(ID_MATERIA, NOMBRE_MATERIA, CARGA_HORARIA_MINIMA, CARRERA, AÑO_CURSO, CUATRIMESTRE) 
VALUES('OEMP', 'Organización Empresarial', 100, 'TUPR', 1, 1)
INSERT INTO MATERIAS(ID_MATERIA, NOMBRE_MATERIA, CARGA_HORARIA_MINIMA, CARRERA, AÑO_CURSO, CUATRIMESTRE) 
VALUES('PRG3', 'Programación III', 100, 'TUPR', 1, 1)
INSERT INTO MATERIAS(ID_MATERIA, NOMBRE_MATERIA, CARGA_HORARIA_MINIMA, CARRERA, AÑO_CURSO, CUATRIMESTRE) 
VALUES('PROF', 'Práctica Profesional', 100, 'TUPR', 1, 1)
-- OTRA CARRERA
INSERT INTO CARRERAS(ID_CARRERA, NOMBRE_CARRERA, PLAN_AÑO, DOC_HABILITANTE)
VALUES('TSAD', 'TECNICATURA SUPERIOR EN ADMINISTRACION', '2005', 'Ordenanza 1056/05 MIN EDUCACION')

--MATERIAS
INSERT INTO MATERIAS(ID_MATERIA, NOMBRE_MATERIA, CARGA_HORARIA_MINIMA, CARRERA, AÑO_CURSO, CUATRIMESTRE) 
VALUES('ADG1', 'Administración General I (Integradora)', 192, 'TSAD', 1, 1)
INSERT INTO MATERIAS(ID_MATERIA, NOMBRE_MATERIA, CARGA_HORARIA_MINIMA, CARRERA, AÑO_CURSO, CUATRIMESTRE) 
VALUES('MATG', 'Matemática General', 96, 'TSAD', 1, 1)
INSERT INTO MATERIAS(ID_MATERIA, NOMBRE_MATERIA, CARGA_HORARIA_MINIMA, CARRERA, AÑO_CURSO, CUATRIMESTRE) 
VALUES('INF1', 'Informática I', 100, 'TSAD', 1, 1)
INSERT INTO MATERIAS(ID_MATERIA, NOMBRE_MATERIA, CARGA_HORARIA_MINIMA, CARRERA, AÑO_CURSO, CUATRIMESTRE) 
VALUES('PRSC', 'Problemática Social Contemporánea I', 100, 'TSAD', 1, 1)
INSERT INTO MATERIAS(ID_MATERIA, NOMBRE_MATERIA, CARGA_HORARIA_MINIMA, CARRERA, AÑO_CURSO, CUATRIMESTRE) 
VALUES('ECO1', 'Economía I', 100, 'TSAD', 1, 1)
INSERT INTO MATERIAS(ID_MATERIA, NOMBRE_MATERIA, CARGA_HORARIA_MINIMA, CARRERA, AÑO_CURSO, CUATRIMESTRE) 
VALUES('PSIO', 'Psicología de las Organizaciones', 100, 'TSAD', 1, 1)
INSERT INTO MATERIAS(ID_MATERIA, NOMBRE_MATERIA, CARGA_HORARIA_MINIMA, CARRERA, AÑO_CURSO, CUATRIMESTRE) 
VALUES('AMES', 'Ambiente Economía y Sociedad', 100, 'TSAD', 1, 1)
INSERT INTO MATERIAS(ID_MATERIA, NOMBRE_MATERIA, CARGA_HORARIA_MINIMA, CARRERA, AÑO_CURSO, CUATRIMESTRE) 
VALUES('LEG1', 'Legislación I', 100, 'TSAD', 1, 1)
INSERT INTO MATERIAS(ID_MATERIA, NOMBRE_MATERIA, CARGA_HORARIA_MINIMA, CARRERA, AÑO_CURSO, CUATRIMESTRE) 
VALUES('ESTS', 'Estado y Sociedad', 100, 'TSAD', 1, 1)
INSERT INTO MATERIAS(ID_MATERIA, NOMBRE_MATERIA, CARGA_HORARIA_MINIMA, CARRERA, AÑO_CURSO, CUATRIMESTRE) 
VALUES('SEM1', 'Seminario I: Contabilidad para Administradores', 100, 'TSAD', 1, 1)
INSERT INTO MATERIAS(ID_MATERIA, NOMBRE_MATERIA, CARGA_HORARIA_MINIMA, CARRERA, AÑO_CURSO, CUATRIMESTRE) 
VALUES('SEM2', 'Seminario II: Elementos de Contabilidad', 100, 'TSAD', 1, 1)

INSERT INTO MATERIAS(ID_MATERIA, NOMBRE_MATERIA, CARGA_HORARIA_MINIMA, CARRERA, AÑO_CURSO, CUATRIMESTRE) 
VALUES('ADG2', 'Administración General II (Integradora)', 100, 'TSAD', 2, 1)
INSERT INTO MATERIAS(ID_MATERIA, NOMBRE_MATERIA, CARGA_HORARIA_MINIMA, CARRERA, AÑO_CURSO, CUATRIMESTRE) 
VALUES('INF2', 'Informática II', 100, 'TSAD', 2, 1)
INSERT INTO MATERIAS(ID_MATERIA, NOMBRE_MATERIA, CARGA_HORARIA_MINIMA, CARRERA, AÑO_CURSO, CUATRIMESTRE) 
VALUES('COMO', 'Comportamiento Organizacional', 100, 'TSAD', 2, 1)
INSERT INTO MATERIAS(ID_MATERIA, NOMBRE_MATERIA, CARGA_HORARIA_MINIMA, CARRERA, AÑO_CURSO, CUATRIMESTRE) 
VALUES('ESTI', 'Estadística', 100, 'TSAD', 2, 1)
INSERT INTO MATERIAS(ID_MATERIA, NOMBRE_MATERIA, CARGA_HORARIA_MINIMA, CARRERA, AÑO_CURSO, CUATRIMESTRE) 
VALUES('ECO2', 'Economía II', 100, 'TSAD', 2, 1)
INSERT INTO MATERIAS(ID_MATERIA, NOMBRE_MATERIA, CARGA_HORARIA_MINIMA, CARRERA, AÑO_CURSO, CUATRIMESTRE) 
VALUES('LEG2', 'Legislación II - Derecho Público', 100, 'TSAD', 2, 1)
INSERT INTO MATERIAS(ID_MATERIA, NOMBRE_MATERIA, CARGA_HORARIA_MINIMA, CARRERA, AÑO_CURSO, CUATRIMESTRE) 
VALUES('ADES', 'Administración Estatal', 100, 'TSAD', 2, 1)
INSERT INTO MATERIAS(ID_MATERIA, NOMBRE_MATERIA, CARGA_HORARIA_MINIMA, CARRERA, AÑO_CURSO, CUATRIMESTRE) 
VALUES('GRHU', 'Gestión de Recursos Humanos', 100, 'TSAD', 2, 1)
INSERT INTO MATERIAS(ID_MATERIA, NOMBRE_MATERIA, CARGA_HORARIA_MINIMA, CARRERA, AÑO_CURSO, CUATRIMESTRE) 
VALUES('FITC', 'Finanzas y Técnicas Contables', 100, 'TSAD', 2, 1)
INSERT INTO MATERIAS(ID_MATERIA, NOMBRE_MATERIA, CARGA_HORARIA_MINIMA, CARRERA, AÑO_CURSO, CUATRIMESTRE) 
VALUES('SEM3', 'Seminario III: Costos', 100, 'TSAD', 2, 1)
INSERT INTO MATERIAS(ID_MATERIA, NOMBRE_MATERIA, CARGA_HORARIA_MINIMA, CARRERA, AÑO_CURSO, CUATRIMESTRE) 
VALUES('SEM4', 'Seminario IV: Impuestos', 100, 'TSAD', 2, 1)

SELECT * FROM USUARIOS
SELECT * FROM ALUMNOS
select * from CARRERAS
select * from INSC_ALUM_CARRERA


insert INSC_ALUM_CARRERA( ALUMNO, CARRERA, AÑO, CUATRIMESTRE, ESTADO)
VALUES( 5, 'TUPR', YEAR(GETDATE()), 2, 1)

update usuarios 
set tipousuario = 3 
where id_usuario = 2

select c.NOMBRE_CARRERA from insc_alum_carrera i inner join alumnos a on i.ALUMNO = a.ID_ALUMNO
inner join carreras c on i.CARRERA = c.ID_CARRERA
where ID_ALUMNO = 1

--PARA CARGAR LOS USUARIOS 
UPDATE ALUMNOS SET USUARIO = 'AL.'+CUIL
UPDATE DOCENTES SET USUARIO = 'DO.'+CUIL

USE TPCSYSACAD

select i.ID_INSCRIPCION_CARRERA, c.ID_CARRERA, c.NOMBRE_CARRERA 
from insc_alum_carrera i RIGHT join alumnos a on i.ALUMNO = a.ID_ALUMNO 
inner join carreras c on i.CARRERA = c.ID_CARRERA 
inner join USUARIOS u on a.ID_ALUMNO = u.ID_USUARIO
where u.ID_USUARIO = 1